### ISSUE TITLE
Create Account SDK throws exception - despite successful execution

### ISSUE THREAD

**Issue by r1jsheth** [CurrencyCloud/currencycloud-java#148]
I am facing issue in
`currencyCloudClient.createAccount(account)`
It is throwing exception (exception attached below) and **despite on the demo account it creates a sub account**.
I am using this file `src/test/java/com/currencycloud/examples/CurrencyCloudCookbook.java`

And added these few lines of code.

#### Code
```
Account account = client.createAccount(new Account(
    "Coockbook",
    "company",
    "BLR",
    "BLR",
    "560068",
    "IN"
    )
);
```

#### Exception
```
Exception in thread "main" ---
exception_type: "UnexpectedException"
platform: "Java 18.0.1.1 (Oracle Corporation)"
request: null
inner_error: "java.lang.reflect.InaccessibleObjectException: Unable to make protected\
  \ final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)\
  \ throws java.lang.ClassFormatError accessible: module java.base does not \"opens\
  \ java.lang\" to unnamed module @307f6b8c"

	at com.currencycloud.client.ExceptionTransformer.aroundInvoke(ExceptionTransformer.java:23)
	at si.mazi.rescu.InterceptedInvocationHandler.invoke(InterceptedInvocationHandler.java:42)
	at com.currencycloud.client.Reauthenticator.aroundInvoke(Reauthenticator.java:23)
	at si.mazi.rescu.InterceptedInvocationHandler.invoke(InterceptedInvocationHandler.java:42)
	at jdk.proxy2/jdk.proxy2.$Proxy4.createAccount(Unknown Source)
	at com.currencycloud.client.CurrencyCloudClient.createAccount(CurrencyCloudClient.java:157)
	at com.currencycloud.examples.CurrencyCloudCookbook.runCookBook(CurrencyCloudCookbook.java:51)
	at com.currencycloud.examples.CurrencyCloudCookbook.main(CurrencyCloudCookbook.java:30)
```

#### Screenshot of account created from the dashboard
<img width="1244" alt="Screenshot 2022-07-29 at 1 22 10 PM" src="https://user-images.githubusercontent.com/25662252/181711633-3d639cf9-a8cc-46e8-901c-812c6dd1ad81.png">

**Comment by r1jsheth** [comment]
Moreover, I tried with JDK 17 - the same issue persist.
<img width="1158" alt="Screenshot 2022-08-10 at 2 21 30 PM" src="https://user-images.githubusercontent.com/25662252/183858877-78fe4e1c-6f8c-4bbc-aee3-e29b0ea95548.png">

**Comment by sivasquared** [comment]
We are running into the same exact issue described above.

**Comment by sivasquared** [comment]
Looks like failures were allowed for jdk17 from this commit
https://github.com/CurrencyCloud/currencycloud-java/pull/143/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R27

**Comment by jonathancouchman** [comment]
Prior to this commit we were not testing with JDK 17, this commit added the test, but also allowed for the tests to fail since we had not comprehensively tested with JDK 17.

We are currently investigating the JDK 17 issues to add full support for this version

**Comment by sivasquared** [comment]
Thanks for investing @jonathancouchman. 

Do you have an estimate for when JDK 17 will be fully supported? We're going through a build at the moment and would like to understand how this timeline would affect it.

**Comment by jonathancouchman** [comment]
It seems the issue is with one of the dependencies, https://github.com/cglib/cglib, that does not support JDK 17 and is no longer in active development.

We will need to implement an alternative solution to resolve the issue. As a short term work around you can set the following JVM argument at runtime (if that is possible for you)

--add-opens java.base/java.lang=ALL-UNNAMED

We will update the ticket once we have found a suitable solution

**Comment by sivasquared** [comment]
Thanks for the suggestion Jonathan, that did the trick to unblock us 🎉

**Comment by Tsvetalin-Yordanov** [comment]
Hi , as I also have the same problem I would like to ask if you have another solution or for the time being the fix remains with adding the 
--add-opens java.base/java.lang=ALL-UNNAMED

**Comment by hudson155** [comment]
<img width="805" alt="image" src="https://github.com/CurrencyCloud/currencycloud-java/assets/1360420/0a51e041-81b4-47e5-bf98-331e232d890b">
Should this project move to ByteBuddy?

**Comment by hudson155** [comment]
@jonathancouchman any idea when Java 17 (and 24) will be supported?

**Comment by niall-logue** [comment]
Hi @hudson155, 
The SDK was migrated from cglib to ByteBuddy as of `5.11.0` and Java 17 is now supported. We are not yet testing with Java 24.

**Comment by hudson155** [comment]
Wonderful, thanks for your help!!
