### ISSUE TITLE
Exceptions retrieving Swift payment tracking info

### ISSUE THREAD

**Issue by rnunn-bound** [CurrencyCloud/currencycloud-java#149]
When calling `CurrencyCloudClient.getPaymentTrackingInfo`, we get the following error generated:
```

exception_type: "ApiException"
platform: "Java 17.0.4 (Eclipse Adoptium)"
request:
  parameters: {}
  verb: "get"
  url: "https://api.currencycloud.com/v2/payments/<payment-id>/tracking_info"
response:
  status_code: 200
  date: null
  request_id: null
error_code: null
errors: []
at com.currencycloud.client.exception.ApiException.create(ApiException.java:71)
  at com.currencycloud.client.ExceptionTransformer.aroundInvoke(ExceptionTransformer.java:19)
  at si.mazi.rescu.InterceptedInvocationHandler.invoke(InterceptedInvocationHandler.java:42)
  at com.currencycloud.client.Reauthenticator.aroundInvoke(Reauthenticator.java:23)
  at si.mazi.rescu.InterceptedInvocationHandler.invoke(InterceptedInvocationHandler.java:42)
  at jdk.proxy2/jdk.proxy2.$Proxy24.getPaymentTrackingInfo(Unknown Source)
  at com.currencycloud.client.CurrencyCloudClient.getPaymentTrackingInfo(CurrencyCloudClient.java:1057)
  at com.bndrts.service.external.CurrencycloudWrapper.lambda$getPaymentTrackingInfo$7(CurrencycloudWrapper.java:124)
  at com.bndrts.service.external.CurrencycloudWrapper.lambda$callOnBehalfOf$11(CurrencycloudWrapper.java:154)
  at com.currencycloud.client.CurrencyCloudClient.onBehalfOfDo(CurrencyCloudClient.java:121)
  at com.bndrts.service.external.CurrencycloudWrapper.callOnBehalfOf(CurrencycloudWrapper.java:151)
  at com.bndrts.service.external.CurrencycloudWrapper.getPaymentTrackingInfo(CurrencycloudWrapper.java:123)
  at com.bndrts.service.external.CCPaymentInstructionService.paymentReceived(CCPaymentInstructionService.java:226)
  at com.bndrts.service.external.CCPaymentInstructionService.processPayment(CCPaymentInstructionService.java:211)
  at java.base/java.util.ArrayList.forEach(Unknown Source)
  at com.bndrts.service.external.CCPaymentInstructionService.processCompletedSwiftPayments(CCPaymentInstructionService.java:203)
  at com.bndrts.service.external.SwiftPaymentReceivedJob.execute(SwiftPaymentReceivedJob.java:24)
  at com.bndrts.messaging.consumer.ScheduledEventHandler.lambda$execute$1(ScheduledEventHandler.java:43)
  at com.bndrts.service.infrastructure.MDCPropagatingExecutorServiceDecorator.lambda$withMDC$0(ExecutorFactory.java:152)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
Caused by: ResponseException{errorCode='null', errorMessages=null}
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
  at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
  at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
  at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:123)
  at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:278)
  at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:145)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
  at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
  at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
  at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
  at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
  at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
  at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
  at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
  at com.currencycloud.client.AutoAuthenticator.aroundInvoke(AutoAuthenticator.java:26)
  at si.mazi.rescu.InterceptedInvocationHandler.invoke(InterceptedInvocationHandler.java:42)
  at com.currencycloud.client.ExceptionTransformer.aroundInvoke(ExceptionTransformer.java:17)
  ... 20 more
```

Digging a bit deeper, the root cause seems to be that we're getting an empty array for the `charge_amount` field in our `payment_events`:
```json
{
    "uetr": "...",
    "transaction_status": {
        "status": "completed",
        "reason": null
    },
    "initiation_time": "2022-09-06T00:16:20+00:00",
    "completion_time": "2022-09-06T07:52:57+00:00",
    "last_update_time": "2022-09-06T07:53:17+00:00",
    "payment_events": [
        {
            "tracker_event_type": "customer_credit_transfer_payment_status_update",
            "valid": true,
            "transaction_status": {
                "status": "completed",
                "reason": null
            },
            "funds_available": "2022-09-06T07:52:00+00:00",
            "forwarded_to_agent": null,
            "from": "...",
            "to": "...",
            "originator": "...",
            "serial_parties": {
                "debtor": null,
                "debtor_agent": null,
                "intermediary_agent1": null,
                "instructing_reimbursement_agent": null,
                "creditor_agent": null,
                "creditor": null
            },
            "sender_acknowledgement_receipt": "2022-09-06T07:52:57+00:00",
            "instructed_amount": null,
            "confirmed_amount": {
                "currency": "USD",
                "amount": "..."
            },
            "interbank_settlement_amount": null,
            "interbank_settlement_date": null,
            "charge_amount": [],
            "charge_type": null,
            "foreign_exchange_details": null,
            "last_update_time": "2022-09-06T07:53:17+00:00"
        },
...
```
The SDK is attempting to deserialise this empty array to a `com.currencycloud.client.model.PaymentTrackingInfo.Amount` object which then fails with a Jackson exception:
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `com.currencycloud.client.model.PaymentTrackingInfo$Amount` from Array value (token `JsonToken.START_ARRAY`)
```

**Comment by jonathancouchman** [comment]
Thank you for raising this issue. We will investigate

**Comment by jonathancouchman** [comment]
As indicated, the response body has changed so that the charge_amount is an array of Amount objects, not an Amount Object. The SDK code needs updating to reflect this change
