### ISSUE TITLE
getPaymentTrackingInfo returns an exception with a 200 response

### ISSUE THREAD

**Issue by sivasquared** [CurrencyCloud/currencycloud-java#156]
Calling `getPaymentTrackingInfo` (https://developer.currencycloud.com/api-reference/#get-payment-tracking-information) Returns an exception for a valid swift gpi tracked payment.

```
com.currencycloud.client.exception.ApiException: null (HTTP status code: 200)
	at com.currencycloud.client.exception.ApiException.create(ApiException.java:71)
	at com.currencycloud.client.ExceptionTransformer.aroundInvoke(ExceptionTransformer.java:19)
	at si.mazi.rescu.InterceptedInvocationHandler.invoke(InterceptedInvocationHandler.java:42)
	at com.currencycloud.client.Reauthenticator.aroundInvoke(Reauthenticator.java:23)
	at si.mazi.rescu.InterceptedInvocationHandler.invoke(InterceptedInvocationHandler.java:42)
	at jdk.proxy2/jdk.proxy2.$Proxy32.getPaymentTrackingInfo(Unknown Source)
	at com.currencycloud.client.CurrencyCloudClient.getPaymentTrackingInfo(CurrencyCloudClient.java:1057)
```

Calling the api manually for the payment works as expected.

**Comment by jonathancouchman** [comment]
HI, thanks for raising this issue. Could you please tell us which version of the SDK you are seeing this issue with?

**Comment by sivasquared** [comment]
We are using 5.3.0

**Comment by sivasquared** [comment]
Upgrading to the new release 5.4.0 resolves the issue. Sorry for the false alarm here.

**Comment by sivasquared** [comment]
Upgrading to the new release 5.4.0 resolves the issue
